import axios from "axios";
import { FETCH_USER } from "./types";

// action for get current user
export const fetchUser = () => async dispatch => {
  const res = await axios.get("/api/current_user");
  
  dispatch({ type: FETCH_USER, payload: res.data });
};

// action for event token generated by stripe
export const handleToken = token => async dispatch => {
  const res = await axios.post("/api/stripe", token);
  dispatch({ type: FETCH_USER, payload: res.data });
};

/* NOTES
el dispatch viene del redux thunk, porque crea un envudo para 
que cualquier accion se pueda disparar de cualquier parte
y llevarlas todas a modificar el storage
*/